[package]
name = "p2p-comm-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
p2p-comm-core = { path = "../p2p-comm-core" }
eframe = "0.30"
egui = "0.30"
rfd = { version = "0.14", default-features = false, features = ["xdg-portal", "gtk3"] }
tokio = { version = "1.42", features = ["rt-multi-thread"] }

[lints]
workspace = true
